development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  pool: 5
  database: database_davila_development
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: utf8
  host: localhost
  pool: 5
  database: database_davila_test
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: utf8
  url:  <%= ENV["DATABASE_DAVILA_URL"] %>
  pool: <%= ENV["DB_POOL"] || 5 %>
